let OPTIONS = {
    district: [
        { label: 'all', value: null, single: true },
        {
            label: 'districts.olmazor',
            value: 'olmazor',
            ru: 'Алмазарский',
            pid: 544,
        },
        {
            label: 'districts.bektemir',
            value: 'bektemir',
            ru: 'Бектемирский',
            pid: 309,
        },
        {
            label: 'districts.mirobod',
            value: 'mirobod',
            ru: 'Мирабадский',
            pid: 535,
        },
        {
            label: 'districts.mirzo-ulugbek',
            value: 'mirzo-ulugbek',
            ru: 'Мирзо-Улугбекский',
            pid: 524,
        },
        {
            label: 'districts.sergeli',
            value: 'sergeli',
            ru: 'Сергелийский',
            pid: 592,
        },
        {
            label: 'districts.chilonzor',
            value: 'chilonzor',
            ru: 'Чиланзарский',
            pid: 562,
        },
        {
            label: 'districts.uchtepa',
            value: 'uchtepa',
            ru: 'Учтепинский',
            pid: 579,
        },
        {
            label: 'districts.shayhontohur',
            value: 'shayhontohur',
            ru: 'Шайхантахурский',
            pid: 547,
        },
        {
            label: 'districts.yunusobod',
            value: 'yunusobod',
            ru: 'Юнусабадский',
            pid: 501,
        },
        {
            label: 'districts.yakkasaroy',
            value: 'yakkasaroy',
            ru: 'Яккасарайский',
            pid: 593,
        },
        {
            label: 'districts.yangihayot',
            value: 'yangihayot',
            ru: 'Янгихатяский',
            pid: 0,
        },
        {
            label: 'districts.yashnobod',
            value: 'yashnobod',
            ru: 'Яшнабадский',
            pid: 595,
        },
    ],
    keysProperty: [
        { key: 'listingType', type: 'enum' },
        { key: 'rentType', type: 'enum' },
        { key: 'propertyType', type: 'enum' },
        { key: 'latlng', type: 'location' },
        { key: 'roomsCount', type: 'enum' },
        { key: 'totalArea', type: 'input' },
        { key: 'livingArea', type: 'input' },
        { key: 'floor', type: 'input' },
        { key: 'totalFloors', type: 'input' },
        { key: 'ceilingHeight', type: 'input' },
        { key: 'buildType', type: 'enum' },
        { key: 'repair', type: 'enum' },
        { key: 'constructionDate', type: 'inline' },
        { key: 'hasSwimmingPool', type: 'boolean' },
        { key: 'hasFurnishing', type: 'boolean' },
        { key: 'hasBalcony', type: 'boolean' },
        { key: 'hasParking', type: 'boolean' },
        { key: 'hasSecurity', type: 'boolean' },
        { key: 'hasSurveillance', type: 'boolean' },
        { key: 'hasPlayground', type: 'boolean' },
        { key: 'hasSauna', type: 'boolean' },
        { key: 'hasSewage', type: 'boolean' },
        { key: 'hasElectricity', type: 'boolean' },
        { key: 'hasWater', type: 'boolean' },
        { key: 'hasGas', type: 'boolean' },
        { key: 'name', type: 'input' },
        { key: 'description', type: 'input' },
        { key: 'district', type: 'input', single: true },
        { key: 'street', type: 'input', single: true }
    ]
}

module.exports = {OPTIONS}