const OPTIONS = {
    district: [
        { label: 'all', value: null, single: true },
        {
            label: 'districts.olmazor',
            value: 'olmazor',
            ru: 'Алмазарский',
            pid: 544,
        },
        {
            label: 'districts.bektemir',
            value: 'bektemir',
            ru: 'Бектемирский',
            pid: 309,
        },
        {
            label: 'districts.mirobod',
            value: 'mirobod',
            ru: 'Мирабадский',
            pid: 535,
        },
        {
            label: 'districts.mirzo-ulugbek',
            value: 'mirzo-ulugbek',
            ru: 'Мирзо-Улугбекский',
            pid: 524,
        },
        {
            label: 'districts.sergeli',
            value: 'sergeli',
            ru: 'Сергелийский',
            pid: 592,
        },
        {
            label: 'districts.chilonzor',
            value: 'chilonzor',
            ru: 'Чиланзарский',
            pid: 562,
        },
        {
            label: 'districts.uchtepa',
            value: 'uchtepa',
            ru: 'Учтепинский',
            pid: 579,
        },
        {
            label: 'districts.shayhontohur',
            value: 'shayhontohur',
            ru: 'Шайхантахурский',
            pid: 547,
        },
        {
            label: 'districts.yunusobod',
            value: 'yunusobod',
            ru: 'Юнусабадский',
            pid: 501,
        },
        {
            label: 'districts.yakkasaroy',
            value: 'yakkasaroy',
            ru: 'Яккасарайский',
            pid: 593,
        },
        {
            label: 'districts.yangihayot',
            value: 'yangihayot',
            ru: 'Янгихатяский',
            pid: 0,
        },
        {
            label: 'districts.yashnobod',
            value: 'yashnobod',
            ru: 'Яшнабадский',
            pid: 595,
        },
    ],
    keysProperty: [
        'listingType',
        'propertyType',
        'latlng',
        'roomsCount',
        'totalArea',
        'livingArea',
        'floor',
        'totalFloors',
        'ceilingHeight',
        'buildType',
        'repair',
        'constructionDate',
        // 'street',
        // 'city',
        // 'district',
        // 'bathroom',
        'hasSwimmingPool',
        'hasFurnishing',
        'hasBalcony',
        'hasParking',
        'hasSecurity',
        'hasSurveillance',
        'hasPlayground',
        'hasSauna',
        'hasSewage',
        'hasElectricity',
        'hasWater',
        'hasGas',
        // 'marketType',
        'name',
        'description'
    ]
}

module.exports = {OPTIONS}